{% set name = "nbprint" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7bac73c330872b84ed883da8270bc06737ca4765f7e719fc099f87975bbeb77d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - nbprint = nbprint.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >={{ python_min }}
    - ccflow >=0.4.0
    - dominate
    - hydra-core
    - ipywidgets
    - ipython
    - nbconvert-webpdf >=7.11.0
    - nbformat
    - notebook
    - omegaconf
    - pydantic >=2,<3
    - pydantic-extra-types
    - strenum
    - typer

test:
  imports:
    - nbprint
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: http://github.com/timkpaine/nbprint
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A framework for building Jupyter reports with NBConvert
  description: A framework for building Jupyter reports with NBConvert
  dev_url: https://github.com/timkpaine/nbprint

extra:
  recipe-maintainers:
    - timkpaine
