{% set name = "nbprint" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c68fc6a907ec1aa3ba385c058f36bd990052779195dd6401277d77be7c834ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - nbprint = nbprint.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
    - pnpm
    - hatchling >=1.3.1
    - hatch-js
  run:
    - python >={{ python_min }}
    - ccflow >=0.4.0
    - dominate
    - emails
    - hydra-core
    - ipywidgets
    - jinja2
    - lerna >=1.1.0
    - nbconvert-webpdf >=7.11.0
    - nbformat
    - notebook
    - omegaconf
    - pkn
    - pydantic >=2,<3
    - pydantic-extra-types
    - strenum
    - typer
    - typing-extensions

test:
  imports:
    - nbprint
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: http://github.com/timkpaine/nbprint
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A framework for building Jupyter reports with NBConvert
  description: A framework for building Jupyter reports with NBConvert
  dev_url: https://github.com/timkpaine/nbprint

extra:
  recipe-maintainers:
    - timkpaine
